apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-quarkus-app-02
  description: A cool quarkus app
  annotations:
    argocd/app-name: my-quarkus-app-02-bootstrap
    backstage.io/kubernetes-id: my-quarkus-app-02
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: iocanel
    backstage.io/source-location: url:https://github.com/iocanel/my-quarkus-app-02
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: my-quarkus-app-02
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: iocanel/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
  tags:
    - java
    - quarkus
  links:
    - url: https://my-quarkus-app-02-iocanel.apps.qshift.snowdrop.dev/
      title: Quarkus application url
      icon: web
spec:
  type: service
  lifecycle: production
  owner: user:guest
